apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csiclvm-controllers
spec:
  selector:
    matchLabels:
      app: csiclvmagent # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: csiclvmagent # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: storagelake
                  operator: In
                  values:
                  - controller
      containers:
      - image: ghcr.io/tprohofsky/csiclvm:dev
        imagePullPolicy: Always
        name: csiclvm
        env:
        - name: CSI_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
          - mountPath: /var/run/stolake
            name: stolakesocket
          - mountPath: /var/lib/kubelet/plugins
            name: csisocketdir
        command: ["/stolake/csilvm"]
        args: ["-controller", "-proxy", "/var/run/stolake", "-volume-group", "sbvg_datalake", "-unix-addr=/var/lib/kubelet/plugins/datalake.speedboat.seagate.com/csi.sock", "-node-id", spec.nodeName ]
      volumes:
      - name: stolakesocket
        hostPath:
          path: /var/lib/kubelet/device-plugins/stolake.seagate.sock
          type: Socket
      - name: csisocketdir
        hostPath:
          path: /var/lib/kubelet/plugins
          type: DirectoryOrCreate
