
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: storagelake
            operator: In
            values:
            - node
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: clvm-volume
  volumes:
  - name: clvm-volume
    persistentVolumeClaim:
      claimName: nokomis-testme-pvc
