apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testme-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: clvmstorageclass
  resources:
    requests:
      storage: 100Gi
