kind: Service
apiVersion: v1
metadata:
  name: csi-clvm-attacher
  labels:
    app: csi-clvm-attacher
spec:
  selector:
    app: csi-clvm-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-clvm-attacher
spec:
  serviceName: "csi-clvm-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-clvm-attacher
  template:
    metadata:
      labels:
        app: csi-clvm-attacher
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-clvmplugin
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: storagelake
                  operator: In
                  values:
                  - controller
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v3.0.0-rc1
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir

      volumes:
        - hostPath:
            #path: /var/lib/kubelet/plugins/csi-clvm
            path: /var/lib/kubelet/plugins/datalake.speedboat.seagate.com
            type: DirectoryOrCreate
          name: socket-dir
