kind: Service
apiVersion: v1
metadata:
  name: csi-clvm-provisioner 
  labels:
    app: csi-clvm-provisioner 
spec:
  selector:
    app: csi-clvm-provisioner 
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-clvm-provisioner
spec:
  serviceName: "csi-clvm-provisioner"
  replicas: 1
  selector:
    matchLabels:
      app: csi-clvm-provisioner
  template:
    metadata:
      labels:
        app: csi-clvm-provisioner
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-clvmplugin
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: storagelake
                  operator: In
                  values:
                  - controller
      serviceAccountName: csi-provisioner
      containers:
        - name: csi-provisioner
          image: gcr.io/k8s-staging-sig-storage/csi-provisioner:v2.0.0-rc2
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            # path: /var/lib/kubelet/plugins/csi-clvm
            path: /var/lib/kubelet/plugins/datalake.speedboat.seagate.com
            type: DirectoryOrCreate
          name: socket-dir
